### ISSUE TITLE
Edge browser detects wrong version

### ISSUE THREAD

**Issue by tb-mtg** [WhichBrowser/Parser-PHP#104]
I tried your [demo](https://whichbrowser.net/) site with Edge browser and it returned user agent

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763`

but incorrectly says version is 18, but it actually is 44.17763.1.0 as show below from the app settings:

![image](https://user-images.githubusercontent.com/12589600/49564684-83f40800-f978-11e8-8214-6959c557cf32.png)

Can you fix so that is show the correct version?

**Comment by Firegarden** [comment]
Actually I think the version is 18 based on the user agent string info. I think this is not a bug rather its confusing how edge uses both numbering systems.

**Comment by NielsLeenheer** [comment]
Agreed. Edge app versions are not exposed and according to the Edge team, they should not be used to identify the browser.
