### ISSUE TITLE
Not able to detect Chrome

### ISSUE THREAD

**Issue by evead** [WhichBrowser/Parser-PHP#109]
Hello,

We have a list of user agents not parsed by WhichBrowser. Here is one example : 

Mozilla/5.0 (Linux; Android 7.0; SM-J330FN Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36

Regards

**Comment by mariotsi** [comment]
What do you mean with 'not parsed'?
Here https://whichbrowser.net/tryout/ if works fine and returns `Chromium WebView 56 on a Samsung Galaxy J3 (2017) running Android 7.0`

**Comment by evead** [comment]
I mean that the library does not return the browser information. Even when you use the online demo https://whichbrowser.net/tryout/ , it does not return information regarding the browser, it returns only device information.

**Comment by mariotsi** [comment]
How do access the browser information? Since it’s a web view it will be in the `using` property of the browser object.
You can even get the result invoking `toString()` on the browser object (thats gives me `”Chromium WebView 56”`).

**Comment by NielsLeenheer** [comment]
In this case there is no information about the actual browser in the user agent string. It is not Chrome. However, the actual browser is using the Chrome WebView as a rendering engine.
