### ISSUE TITLE
Wrong browser detection

### ISSUE THREAD

**Issue by pocax** [WhichBrowser/Parser-PHP#112]
wrong detection of browser, always show Obigo Q 2A on Opera/UCBrowser/Dolphin Android version.

**Comment by mimmi20** [comment]
@pocax Please add a useragent.

**Comment by pocax** [comment]
- Mozilla/5.0 (Linux; Android 9; Pixel 3 Build/PQ2A.190405.003; rv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Rocket/1.4.0(11337) Chrome/74.0.3729.112 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 9; Pixel 3 Build/PQ2A.190405.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.112 Mobile Safari/537.36
- Mozilla/5.0 (Linux; U; Android 9; en-US; Pixel 3 Build/PQ2A.190405.003) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 Mobile Safari/537.36 UCBrowser/12.10.0.1163 UCTurbo/1.4.2.893
- Mozilla/5.0 (Linux; U; Android 9; Pixel 3 Build/PQ2A.190405.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.112 Mobile Safari/537.36 OPR/40.1.2254.138129

-> its always detected as Obigo Q Dev 2A / Obigo Q 2A

**Comment by NielsLeenheer** [comment]
Okay, the reason for this is the PQ2A in the Build section of the useragent string. Will investigate.

**Comment by NielsLeenheer** [comment]
Found, fixed in f7632b3fa47db56ccfdb64bff0d480fa44ee0ecc and will be included in the next release

**Comment by NielsLeenheer** [comment]
v2.0.38 has been released.
