### ISSUE TITLE
New Edge not detected correctly

### ISSUE THREAD

**Issue by BAnder9447** [WhichBrowser/Parser-PHP#113]
The new Microsoft Edge browser based on Chromium is getting detected as Google Chrome.  Needs to add detection for the new "Edg" user agent that Microsoft is using for the new versions of Edge.

User agent string from new Edge example:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.0 Safari/537.36 **Edg/75.0.139.1**

**Comment by Maggers** [comment]
Please update this when you get a chance as it's impacting HTML5test that people still care about.

**Comment by NielsLeenheer** [comment]
Fixed with commit cb80f32fad0bf64f0ed934f135ec8ab43e24ed47, will be included in an upcoming release.

**Comment by mgol** [comment]
@NielsLeenheer A few months have passed; any chance for a new release?

**Comment by NielsLeenheer** [comment]
v2.0.38 has been released.

**Comment by mgol** [comment]
@NielsLeenheer Could you also update https://whichbrowser.net/ & https://html5test.com/? They still detect the new Edge as Chrome.
