### ISSUE TITLE
Wrong browser information

### ISSUE THREAD

**Issue by wordlesswind** [WhichBrowser/Parser-PHP#116]
I opened https://whichbrowser.net in [QQ](https://play.google.com/store/apps/details?id=com.tencent.mobileqq), but in fact it calls WebView.

![Screenshot_20190526-140853](https://user-images.githubusercontent.com/9050713/58378102-564f5980-7fc0-11e9-9a31-dccea66600c5.jpg)

Mozilla/5.0 (Linux; Android 9; ONEPLUS A6000 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.157 Mobile Safari/537.36 V1_AND_SQ_7.7.6_899_GM_D QQ/7.7.6.3680 NetType/WIFI WebP/0.4.1 Pixel/1080

**Comment by NielsLeenheer** [comment]
The detection looks good to me. What do you believe should be different?

**Comment by wordlesswind** [comment]
The problem is that I didn't use the QQ browser.
"QQ" in UA only indicates that it is social software [QQ](https://play.google.com/store/apps/details?id=com.tencent.mobileqq).
