### ISSUE TITLE
some uncorrect browser detection

### ISSUE THREAD

**Issue by ttrasn** [WhichBrowser/Parser-PHP#117]
* basilisk browser 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.9) Gecko/20100101 Goanna/4.1 Firefox/60.9 Basilisk/20190211
returned : Firefox 60.9 on Windows 10

* Datanyze browser extension
Mozilla/5.0 (X11; Datanyze; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
returned : Chrome 65 on Linux

* firefox focus
Mozilla/5.0 (Linux; Android 8.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.0.2 Chrome/66.0.3359.126 Mobile Safari/537.36
returned : Chrome 66 on Android 8.0.0

* iron safari
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3400.0 Iron Safari/537.36
returned : Chrome Dev 65.0.3400.0 on Windows 10

* kiwi chrome
Mozilla/5.0 (Linux; Android 9; Pixel 3; Windows 10 Mobile) AppleWebKit/537.36 (KHTML, like Gecko) Kiwi Chrome/63.0.3239.111 Mobile Safari/537.36
returned :Chrome 63 on a Windows 10 Mobile running Android 9

* mint browser 
Mozilla/5.0 (Linux; U; Android 7.0; fa-ir; TRT-L21A Build/HUAWEITRT-L21A) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/Mint Browser/1.5.3
returned : Chrome 61 on a Huawei Enjoy 7 Plus running Android 7.0

* opera touch 
Mozilla/5.0 (Linux; Android 7.0; SM-G610F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/73.0.3683.90 Mobile Safari/537.36 OPT/1.17.66
returned : Chrome Dev 73.0.3683.90 on a Samsung Galaxy J7 Prime running Android 7.0

* Oppo browser
Mozilla/5.0 (Linux; U; Android 5.1; en-us; OPPO A37m Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.134 Mobile Safari/537.36 OppoBrowser/4.9.3
returned : Chrome 53 on an Oppo A37m running Android 5.1

* RDDocuments
Mozilla/5.0 (iPhone; CPU iPhone OS 12_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.3 Mobile/15E148 Safari/ RDDocuments/6.9.1.622
returned: Safari on an Apple iPhone running iOS 12.3

* tenta browser
Mozilla/5.0 (Linux; U; Android 5.1; fa; HTC Desire 728G dual sim) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Tenta/2.10.10 Safari/537.36
returned : Chrome 64 on a HTC Desire 728G running Android 5.1

* vivo browser
Mozilla/5.0 (Linux; Android 5.0.2; vivo Y51L Build/LRX22G; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/5.9.1.1
returned : Chromium WebView 62 on a Vivo Y51L running Android 5.0.2

* [Wappalyzer ](https://www.wappalyzer.com/)
Mozilla/5.0 (compatible; Wappalyzer)
returned: an unknown browser

* wk browser
Mozilla/5.0 (Linux; Android 5.1.1; SM-J320H Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36 wkbrowser 4.6.17 1904263 js 5.1.1 newfocus
returned : Chromium WebView 55 on a Samsung Galaxy J3 running Android 5.1.1

**Comment by NielsLeenheer** [comment]
Added Oppo Browser, Vivo Browser, Firefox Focus and Opera Touch. Will be included in the next release.

**Comment by NielsLeenheer** [comment]
v2.0.38 has been released.
