### ISSUE TITLE
Galaxy S10 not being detected

### ISSUE THREAD

**Issue by gaiustemple** [WhichBrowser/Parser-PHP#120]
```
Mozilla/5.0 (Linux; Android 9; SM-G973F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.111 Mobile Safari/537.36
```

When trying to parse the above user agent with model number SM-G973F (Galaxy S10) it doesn't show "Samsung Galaxy S10" it just shows "SM-G973F".

This was tested on https://whichbrowser.net/tryout/

I also tested the same user agent but changed the model number just to see where the issue was - changing the model number from SM-G973F to SM-G960F made it parse the manufacturer and model correctly.

**Comment by NielsLeenheer** [comment]
Database has been updated and v2.0.38 has been released.
