### ISSUE TITLE
PLEASE APPLY PATCH TO PHP 7.4 SUPPORT

### ISSUE THREAD

**Issue by darksoftware** [WhichBrowser/Parser-PHP#131]
file: ""vendor/whichbrowser/parser/src/Model/Version.php

line: 254

`$version .= implode('.', $v);`

**Comment by mimmi20** [comment]
see #129

**Comment by reedy** [comment]
> see #129

Which has been merged

**Comment by NielsLeenheer** [comment]
whichbrowser/parser v2.0.38 has been released.
