### ISSUE TITLE
Android and Blackberry browser versions not getting displayed

### ISSUE THREAD

**Issue by ayumi-cloud** [WhichBrowser/Parser-PHP#139]
## Android

User-Agent Example:

```
Mozilla/5.0 (Linux; U; Android 2.3.6; en-us; Nexus S Build/GRK39F) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
```

This UA is from Google Chrome's Dev Tools:

![image](https://user-images.githubusercontent.com/57409060/78452565-de43cc80-7683-11ea-9f27-5048e0c250b1.png)

Running the UA through your tester I get the following result:

![image](https://user-images.githubusercontent.com/57409060/78452583-fc113180-7683-11ea-8c55-f8f44c7041f6.png)

The issue we find is that with Android browsers this repo is not displaying the browser version for them.

We were expecting the following result:

You are using Android Browser `4.0` on a Samsung Nexus S running Android 2.3.6

Surely this package should parse the `Version/4.0` section to add the browser version number.

## Blackberry

![image](https://user-images.githubusercontent.com/57409060/78456792-ab0e3700-769d-11ea-8b18-8f5a6c06f469.png)

```
Mozilla/5.0 (BB10; Touch) AppleWebKit/537.1+ (KHTML, like Gecko) Version/10.0.0.1337 Mobile Safari/537.1+
```

Browser version is blank and expected to use the `Version/10.0.0.1337`

```
Mozilla/5.0 (PlayBook; U; RIM Tablet OS 2.1.0; en-US) AppleWebKit/536.2+ (KHTML, like Gecko) Version/7.2.1.0 Safari/536.2+
```

Browser version is blank and expected to use the `Version/7.2.1.0`

```
Mozilla/5.0 (BlackBerry; U; BlackBerry 9900; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.187 Mobile Safari/534.11+
```

Browser version is blank and expected to use the `Version/7.0.0.187`

## Internet Explorer

The `browser->alias` value, we were expecting to see the value `IE` for that browser (Currently it is blank).

e.g.

```
name: 'Internet Explorer',
version: '11.0',
alias: 'IE'
```

---

Lastly, we found a load of UA's that are not recognized by this package and want to know the best way to write an issue and/or pr.

e.g.

**You are using an unknown browser**

```
Roku4640X/DVP-7.70 (297.70E04154A)
```

Is `Roku Ultra` Set Top box browser User Agent

https://deviceatlas.com/blog/list-of-user-agent-strings#settop

---

bot:

```
e.ventures Investment Crawler (eventures.vc)
```

http://aqtronix.com/useragents/?Action=ShowAgentDetails&Name=e%2Eventures+Investment+Crawler

---

bot:

```
eContext/1.0 (eContext Classification Engine)
```

http://aqtronix.com/useragents/?Action=ShowAgentDetails&Name=eContext+Classification+Engine

etc.

**Comment by NielsLeenheer** [comment]
`Mozilla/5.0 (Linux; U; Android 2.3.6; en-us; Nexus S Build/GRK39F) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1`

The `Version/4.0` in the UA string is not the version of the browser. It is the version of Safari from the time when the WebKit source code was forked and is there for backwards compatibly reasons. Android Browser itself does not have a version number and did not need it, as it was always released as part of the Android operating system. 

Detecting as version 4.0 would be wrong.

**Comment by NielsLeenheer** [comment]
`Mozilla/5.0 (BB10; Touch) AppleWebKit/537.1+ (KHTML, like Gecko) Version/10.0.0.1337 Mobile Safari/537.1+`

The version in the UA string actually refers to the version of the BlackBerry 10 operating system.

**Comment by NielsLeenheer** [comment]
`Mozilla/5.0 (PlayBook; U; RIM Tablet OS 2.1.0; en-US) AppleWebKit/536.2+ (KHTML, like Gecko) Version/7.2.1.0 Safari/536.2+`

The `Version/7.2.1.0` is not the version of the browser, but is there for backwards compatibility reasons. It had to be at least as high as 7.0 because that is the version the latest mobile phones from BlackBerry from that era used. Otherwise the browser would probably be detected as a legacy Blackberry 2.1 phone by existing browser detection scripts. 

You'll notice the version is "7" . "2.1.0" - the same as the OS version.

**Comment by NielsLeenheer** [comment]
`Mozilla/5.0 (BlackBerry; U; BlackBerry 9900; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.187 Mobile Safari/534.11+`

The version is again the version of the BlackBerry operating system. The actual version of the browser is something completely different and not exposed.

**Comment by ayumi-cloud** [comment]
@NielsLeenheer yah I see your point, sorry when I tested your last comment, I was seeing these results:

![image](https://user-images.githubusercontent.com/57409060/79139822-e7811780-7dae-11ea-9ce1-17c3abb581e0.png)

I just thought `Blackberry` is the same like the `Apple IOS` where say an `iPad` is using the operating system `9.3.5` and the `Safari built-in browser` would be the same version at `9.3.5`

~Not used blackberry so not 100% sure.

**Comment by ayumi-cloud** [comment]
I see, I thought it was maybe the same like Apple IOS where the operating system was the same version as Safari.

I will close this issue - as the default browsers don't have a version number.
