### ISSUE TITLE
Kindle and Dalvik Browsers not detected

### ISSUE THREAD

**Issue by ayumi-cloud** [WhichBrowser/Parser-PHP#162]
Link for Kindle User Agent Examples: 

- https://developers.whatismybrowser.com/useragents/explore/operating_platform/kindle/

- https://developers.whatismybrowser.com/useragents/explore/software_name/kindle-browser/

There seems to be a few groups:

### Silk Browser

```
Mozilla/5.0 (Linux; Android 5.1.1; AFTT Build/LVY48F) AppleWebKit/537.36 (KHTML, like Gecko) Silk/62.7.2 like Chrome/62.0.3202.84 Safari/537.36
```

Works fine.

```
Browser Name: Silk
Browser Version: 62.7.2
```

### Kindle Browser

```
Mozilla/5.0 (Linux; U; en-US) AppleWebKit/528.5+ (KHTML, like Gecko, Safari/528.5+) Version/4.0 Kindle/3.0 (screen 600x800; rotate)
```

Comes up blank at the moment.

Expected results:

```
Browser Name: Kindle Browser
Browser Version: 3.0
```

### Android Browser

```
Mozilla/5.0 (Linux; U; Android 4.3; en-gb; Amazon Kindle Fire Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

Works fine.

```
Browser Name: Android Browser
Browser Version:
```

### Dalvik (software)

Link: https://en.wikipedia.org/wiki/Dalvik_(software)

```
Dalvik/2.1.0 (Linux; U; Android 5.1.1; KFARWI Build/LVY48F)
```

Comes up blank at the moment.

Expected results:

```
Browser Name: Android Browser
Browser Version: 2.1.0
```

@NielsLeenheer thoughts ?

**Comment by NielsLeenheer** [comment]
### Dalvik

Dalvik is not an indication of "Android Browser". It is the default UA string for non-WebView network requests on Android. So Dalvik actually ensures it is not the Android Browser. Dalvik is the name of the VM runtime that Android used by default up til version 4.4. So at most you can say it is an app running on Android.

**Comment by ayumi-cloud** [comment]
Thank you! Amazing how much knowledge you have on user agents!

Will close this issue as well - as everything is working as expected!
