### ISSUE TITLE
Admins please read this

### ISSUE THREAD

**Issue by summercms** [WhichBrowser/Parser-PHP#212]
Hello,

Sorry to mass open many issues, we have been running various tests against your repo on many browsers and see if your package can detect them or not?

We haven't finished yet and still running some tests and will open a few more issues up (probably)?

We just going through this list of browsers right now found here and running tests: https://udger.com/resources/ua-list#Browser

> We hope to finish running tests in next few days (less than a week) and then start writing the pull requests!

So far your package is finding around 70% of the browsers - so good work.

Please can you tag me or message back when you are free and we can start working on a bunch of pull requests for you - to update this package and make it up to date. (It seems like it detects old browsers well and newer browsers not so well).

Lastly, we have put regex and notes on each issue to help with the pull requests. There are a few issues that we need to talk to you about versions and a few complicated fixes.

But we think we can code 98% of all the opened issues without any help.

We intend to add the UA's to the testing folder as well.

Kind regards,

Ayumi.

@NielsLeenheer 

@mariotsi

**Comment by ayumi-cloud** [comment]
p.s. I have emailed @NielsLeenheer to let you know.

**Comment by NielsLeenheer** [comment]
Thanks for opening all of these issues and your willingness to create pull requests for it! 

There is a lot of interesting information here, but I can also see some errors. And there may also be some fundamental differences to the approach this library is using. 

Take for example the Maple browser on Samsung television devices. I'm conflicted on how to detect this. Maple is an internal code name for the browser, not a consumer facing name. It was always labeled as "Web Browser". To me that is a big distinction. What also not helps it that Samsung sometimes refers to Maple as a development platform (for HTML based smart tv apps) and apps build using that development platform sometimes also use the token Maple in the UA string. So far I've not shown the name here, but used Maple as an identifier that we are dealing with a Samsung television device.

Or take the Sony PSP browser. I know it is a NetFront based browser. But is can not be detected as "NetFront", because it is a browser build in house by Sony itself, based on NetFront technology and source code. It is not a NetFront browser released by the Access. I am also hesitant to call it the "PSP Browser" or something to that effect, because on the PlayStation itself it is labeled "Internet Browser". And "Internet Browser" is too generic to be used as a browser name for detection purposes".

I want to land as much of this as possible, but I do have to go over each individual item. I'm sure most can be landed as it, but some of the issues you've opened are not as straightforward as they seem.

So please, continue opening issues and making PR's, but I am hesitant to land all these changes as one big PR.

Relatively safe changes, like new browsers could be bundled together in one PR. But please use different commits in the PR for the different browsers. And please be aware that any change also requires that you add examples of the UA string to the test suite. 
And changes should also not affect the existing UA strings in the test suite. 

Any change that does change the detection of existing UA strings should definitely be in a separate PR, because it affects backwards compatibility.

Thanks again!
Niels

**Comment by ayumi-cloud** [comment]
@NielsLeenheer I've bundled all the desktop and mobile browsers in a single pr at the moment, including the tests, makes a total of 18 file changes.

I was hoping to just bundle these common browsers in a single pr and then open a new pr for the email browsers and another pr for the feed reader browsers etc.

Will tag you when I'm done with the desktop and mobile browser pr and happy to adjust things as you see fit.

**Comment by ayumi-cloud** [comment]
Not sure where to add the two Opera browsers?

The following: 

- `Opera GX` https://github.com/WhichBrowser/Parser-PHP/issues/239

- `Opera Neon` https://github.com/WhichBrowser/Parser-PHP/issues/141

Either to the main list, on this page: https://github.com/WhichBrowser/Parser-PHP/blob/master/data/applications-browsers.php

Or update the code here: https://github.com/WhichBrowser/Parser-PHP/blob/4899110cd2f87b01e04ced62dbb9dec541031dee/src/Analyser/Header/Useragent/Browser.php#L504

I thought it best to leave a note here and let you decide.

**Comment by ayumi-cloud** [comment]
I might need some help writing the `os` for these two - not sure haven't looked deeply into the `os` code lines yet.

---

Pure Browser and PureOS Engine not detected. Can be added in a separate pr as it needs the `browser` and `os` updating - https://github.com/WhichBrowser/Parser-PHP/issues/240

---

Same with issue: Realme Browser and Realme ColorOS Engine not detected https://github.com/WhichBrowser/Parser-PHP/issues/242

**Comment by ayumi-cloud** [comment]
I should disclose my goals, my plan is to try and integrate as many missing desktop, mobile and offline browsers from the lists found here:

- https://udger.com/resources/ua-list#Browser
- https://github.com/browscap/browscap/blob/master/resources/browsers/browser.json

As our company is going to be using your package to detect browsers.

So I will spending most of this month helping to update things.

**Comment by ayumi-cloud** [comment]
Question: Why this repo doesn't use `Strict` with various code lines?

For example:

https://github.com/WhichBrowser/Parser-PHP/blob/3810e9aceed8acab7f27d1145579cae30eb59ac0/src/Analyser/Corrections.php#L83

Uses `==`

```php
if ($this->data->os->name == 'Series60' && $this->data->browser->name == 'Internet Explorer') {
```

I would of thought it should be this `===`

```php
if ($this->data->os->name === 'Series60' && $this->data->browser->name === 'Internet Explorer') {
```

**Comment by ayumi-cloud** [comment]
Work Progress:

- [ ] Round 1 of browsers to be added

- [ ] Round 2 of browsers to be added

- [ ] Chat-app browsers to be added

- [ ] Email client browsers to be added

Will tag you when I'm finished for you to review and merge the pr's.

**Comment by ayumi-cloud** [comment]
Issues with this package:

https://github.com/WhichBrowser/Parser-PHP/pull/325

https://github.com/WhichBrowser/Parser-PHP/pull/330

https://github.com/WhichBrowser/Parser-PHP/pull/347

**Comment by ayumi-cloud** [comment]
@NielsLeenheer  

Hi,

Just to let you know I've finished adding all the missing browsers. I have manually tested each one.

Fingers crossed you can merge them all.

Any changes or issues please tag me, because our company is using this package and when I was adding the browsers I was updating our api to match each one.

Many thanks,

Ayumi.

**Comment by NielsLeenheer** [comment]
Thank you. I’ll go over the PRs. Given the huge number of them it may take a bit of time, but I think most of them can be merged without any issues.

**Comment by mariotsi** [comment]
As soon as those PRs are merged and @ayumi-cloud work is done I will replicate the change in Parser-JavaScript. Thanks for the leg work here!

**Comment by ayumi-cloud** [comment]
Thanks to both of you for the trust.

**Comment by ayumi-cloud** [comment]
@NielsLeenheer @mariotsi Hi, hope all is well, just wanted to ask. Would it be a good idea to merge all these pr's into a separate branch before adding them to the `master` branch. Then we can further test all of them for any conflicts etc.

**Comment by ayumi-cloud** [comment]
Just to let you know, I'm going to be finishing off coding a large project in September and then either near the end of September or in October, I will finish off coding and updating all the pull requests and issues I have opened up in this repo.

**Comment by mariotsi** [comment]
Perfect!

**Comment by ayumi-cloud** [comment]
The Travis setup is completely broken and I'm wasting many hours trying to get a pr to pass through the testing, as it always fails for no good reason! Totally fed-up now! Just going to submit every pr with PHP5 in Travis turned off!

![image](https://user-images.githubusercontent.com/57409060/94368128-8e960900-00da-11eb-981d-d415016557c0.png)

Will use this code: https://github.com/WhichBrowser/Parser-PHP/blob/1850dae67f3e3e4ea86329484b191b49332d6345/.travis.yml

If want you php5 then add the travis file after I have submitted all the pr's.

![image](https://user-images.githubusercontent.com/57409060/94368440-fc8f0000-00db-11eb-89f8-d0b27212ab50.png)

Note PHP 7 and 8 should be supported in 4th quarter this year!

**Comment by ayumi-cloud** [comment]
@NielsLeenheer @mariotsi

Ok, just to let you both know - I have now finished adding all the `browsers` and `social media platforms` to this repo. Just tag me with regards to any changes, when you get a chance to go through the pull requests.

Thanks,

Ayumi.

**Comment by ayumi-cloud** [comment]
Finished coding all the pr's I needed to add to this repo now.

Two issues I leave for you guys to code are: https://github.com/WhichBrowser/Parser-PHP/issues/255 and https://github.com/WhichBrowser/Parser-PHP/issues/253 as I'm not sure how to write the solutions for these?

Any issues with the pr's tag me and I will update the pr's accordingly.

Please can you add a new semantic version when all the pr's are merged so I can back test this repo for any issues etc.

Thanks.

**Comment by ayumi-cloud** [comment]
Search Engines currently force the repo to search many regex patterns, giving a poor performance. To increase performance I decided to code a single regex pattern and then a more detailed search gets done using an external class, a working example is here: https://github.com/WhichBrowser/Parser-PHP/pull/565/files

**Comment by patrick-yi-82** [comment]
I was wondering when the next batch of pull requests will be merged?

**Comment by ayumi-cloud** [comment]
@NielsLeenheer @mariotsi

Just to let you know, I have now finished updating and creating pr's for this repo. Sorry to have created so many pr's I was coding my application at the same time as this repo and testing this repo as I was coding both repo's at the same time and fixing any problems that failed testing.

Please go ahead and start merging these pr's whenever you got free time.

Please tag me with any issues or any `browser name` changes as I have hard coded the the browser names into our api.

Thanks,

Ayu.

**Comment by ayumi-cloud** [comment]
I have merged all the pull requests, except for the following pr's:

https://github.com/WhichBrowser/Parser-PHP/pull/338
https://github.com/WhichBrowser/Parser-PHP/pull/326
https://github.com/WhichBrowser/Parser-PHP/pull/316
https://github.com/WhichBrowser/Parser-PHP/pull/294

I have also cleaned up the code and added some extra code.

I have created a semantic version which can be downloaded here:

https://github.com/ayumi-cloud/Parser-PHP-v3.0.0/releases

I hope the admins can test this version out and merge it into this repo.

**Comment by ayumi-cloud** [comment]
I have merged all the pull requests, except for the following pr's:

https://github.com/WhichBrowser/Parser-PHP/pull/338
https://github.com/WhichBrowser/Parser-PHP/pull/326
https://github.com/WhichBrowser/Parser-PHP/pull/316
https://github.com/WhichBrowser/Parser-PHP/pull/294

I have also cleaned up the code and added some extra code.

I have created a semantic version which can be downloaded here:

https://github.com/ayumi-cloud/Parser-PHP-v3.0.0/releases

I hope the admins can test this version out and merge it into this repo.

p.s. The `3.0.0` version was built off the `master` branch on that repo. I added every pr via a different branch and tested each one separately!

**Comment by mariotsi** [comment]
Thank you @ayumi-cloud . Sorry for the late response. Looks like @NielsLeenheer is currently busy. As soon as he check and approves the changes I'll apply them on the Parser-Javascript version.

**Comment by ayumi-cloud** [comment]
@mariotsi No problem, just tag me and I will keep a look out.

p.s. Travis no longer works anymore and needs to be moved over to Github Actions.

**Comment by ayumi-cloud** [comment]
@NielsLeenheer @mariotsi 

I would be very grateful if you could create a new repo titled: `whichbrowser/parser-laravel` and upload all these files to it.

Link: https://github.com/ayumi-cloud/Parser-Laravel

(We're using Laravel and created this wrapper which I would prefer if it got maintained over here as an official wrapper).

Thanks.

**Comment by NielsLeenheer** [comment]
My apologies for being really slow with responding. As @mariotsi mentioned, I am really busy at the moment and will look at all the changes in the coming weeks. @ayumi-cloud thanks so much for your patience so far. 

I will probably have some time next week and I hope to be able to publish a release version before the years end. I'll also look at Travis and the Laravel wrapper.

**Comment by NielsLeenheer** [comment]
I've processed a whole batch of PRs. Some as is, some slightly changed. I did use a clean commit for each of them, to get rid of unrelated files and changes in the original PR. This way I could process the changes much faster instead of having to rebase the PRs and revert some unrelated changes. 

Unfortunately this is all I got time for during the Christmas break. I do hope to find some more time in the coming weeks and will look at the remaining PRs. 

For now, I will release an updated version with all of changes so far. 

Thanks!

**Comment by ayumi-cloud** [comment]
No problem, it took me a whole week to add and test all the pr's to my temporary repo. It's good you got the Github Actions up and running.

Will keep the temporary repo up on my side until all the pr's have been merged and then I will delete it. Still using it for testing purposes.

Also wishing everyone a Happy New Year.

**Comment by summercms** [comment]
It's now been over a year since I created the out standing pull requests.

Sorry I can't wait any longer and decided to merge all the pull requests on a separate repo.

I have rebased every pull request with the master and double checked all the code and updated the pull requests with your suggestions.

People are welcome to download and test out all the merged pull requests here: 

https://github.com/summercms/Parser-PHP-v3.x.x/releases/tag/v3.1.0

Any issues let me know and I will try and update the pull requests in both repos.

Please note that I've got cancer right now and need to start chemo in the coming weeks - so I maybe slow to reply and answer. 

(I needed to merge and get this work done before I focus on my health).

Notes for admins:

Didn't add:

Repo has Chrome 90 and this pr has chrome 88 (not needed): https://github.com/WhichBrowser/Parser-PHP/pull/647
Additions in this pr has been added in other pr's (not needed): https://github.com/WhichBrowser/Parser-PHP/pull/107
Add more semantic constructors (not needed - pr can be deleted): https://github.com/WhichBrowser/Parser-PHP/pull/67

Added:

These two pr's are the exact same, so added just one of them: https://github.com/WhichBrowser/Parser-PHP/pull/532/files and https://github.com/WhichBrowser/Parser-PHP/pull/137

Add `OhHai Browser`: https://github.com/summercms/Parser-PHP-v3.x.x/pull/218/files
Add `CF-UC User Agent` Bot: https://github.com/summercms/Parser-PHP-v3.x.x/pull/221/files
Fix code error, replace `″` with `"`: https://github.com/summercms/Parser-PHP-v3.x.x/issues/190/files
Add `Pandalytics ` bot: https://github.com/summercms/Parser-PHP-v3.x.x/issues/137/files
Cleanup code: https://github.com/summercms/Parser-PHP-v3.x.x/pull/222/files
