### ISSUE TITLE
Add `Roku Ultra` Set Top box browser User Agent to detection

### ISSUE THREAD

**Issue by ayumi-cloud** [WhichBrowser/Parser-PHP#255]
User agent:

```
Roku4640X/DVP-7.70 (297.70E04154A)
```

Is `Roku Ultra` Set Top box browser User Agent

See list found here: https://deviceatlas.com/blog/list-of-user-agent-strings#settop

---

Roku is a `device` and not a browser. You can install Chrome and Firefox Android apps on it.

![image](https://user-images.githubusercontent.com/57409060/95657015-0ec06380-0b0a-11eb-9fb9-2cf3c43e936c.png)

Link: https://www.roku.com/

**Comment by ayumi-cloud** [comment]
I leave the admins to fix this issue.

**Comment by NielsLeenheer** [comment]
Improved Roku detection. Fixed in 2.1.1
