### ISSUE TITLE
Wechat and Facebook Messenger conflict

### ISSUE THREAD

**Issue by ayumi-cloud** [WhichBrowser/Parser-PHP#488]
When looking at the code `messenger` regex id is being used for both Facebook Messenger and WeChat, see screenshot:

![image](https://user-images.githubusercontent.com/57409060/89284942-6b555d00-d647-11ea-96ea-d8e4848cd05b.png)

I suggest splitting them and creating a separate regex id for WeChat.

**Comment by NielsLeenheer** [comment]
This is not a problem. In fact, the id must be a part of the user agent string and is used to optimise the speed of the user agent detection. In this case "messenger" is both in the Facebook Messenger and WeChat user agent string, so it will work properly. Using as little different id's as possible is even preferred for speed.
