### ISSUE TITLE
Device detection error

### ISSUE THREAD

**Issue by vbntv** [WhichBrowser/Parser-PHP#618]
Hello.
In user agents like these, "device" is defined as empty string: 
Mozilla/5.0 (Linux; arm_64; Android 6.0.1; NX549J) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 YaBrowser/20.9.3.85.00 SA/3 Mobile Safari/537.36"
Mozilla/5.0 (Linux; arm; Android 6.0.1; NX549J) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 YaBrowser/20.9.3.85.00 SA/3 Mobile Safari/537.36"

But if you send in the parser the same UA without "arm" or "arm_64" - device is detected correctly.

**Comment by NielsLeenheer** [comment]
Fixed in the upcoming 2.1.1 release.
