### ISSUE TITLE
Incorrect brand name result it's `SmarDTV` and not `SmarD TV`

### ISSUE THREAD

**Issue by summercms** [WhichBrowser/Parser-PHP#625]
The test result is incorrect.

https://github.com/WhichBrowser/Parser-PHP/blob/da24adc4f4f26002673d236e69b91a10f2fd594c/tests/data/television/other.yaml#L74-L77

The brand name is: `SmarDTV` not `SmarD TV` (note the space between the `D` and `TV`), see Google result:

![image](https://user-images.githubusercontent.com/57409060/103816657-3ec1c900-505d-11eb-8443-aa16c304ffb6.png)

### Location in repo

Can't find an exact location, seems to be maybe a fallback method or something?

I was looking at this file:

https://github.com/WhichBrowser/Parser-PHP/blob/master/src/Analyser/Header/Useragent/Device/Television.php

### Set top Box (not TV)

This company seems to make set top boxes and not tv's, see promo videos:

https://www.youtube.com/watch?v=Hec1mecXVbg

https://www.youtube.com/watch?v=2PYC_4qn56w

Not sure if want to create a new category for `Set top boxes` as `TV` doesn't seem to be a good fit for some results.

### Help please

Going to leave this open issue for the admins, I would love to add a pr for this, but not sure where the exact code location is to edit?

**Comment by Sainan** [comment]
I suspect the name is taken verbatim from the headers:
> User-Agent: HbbTV/1.2.1 (+DL; **SmarD TV**; TCL; 1.32.455; 2.002; WOTV/0.1; SmartTvA/3.0.0.0;)
