### ISSUE TITLE
Chrome wrong version Detection

### ISSUE THREAD

**Issue by thedoggybrad** [WhichBrowser/Parser-PHP#672]
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

Result: You are using an unknown browser that imitates Chrome Dev 100.0.4896.127 on Windows 10

Expected Result: You are using Chrome Dev 100.0.4896.127 on Windows 10

**Comment by NielsLeenheer** [comment]
This should have been fixed by last weeks release. Which version are you using?

**Comment by thedoggybrad** [comment]
@NielsLeenheer 

As of this moment here are the results from https://whichbrowser.net/

You are using an unknown browser that imitates Chrome Dev 100.0.4896.127 on Windows 10
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36


As of this moment https://html5test.com outputs:
You are using an unknown browser that imitates Chrome Dev 100.0.4896.127 on Windows 1

**Comment by thedoggybrad** [comment]
As of this moment both https://html5test.com or https://whichbrowser.net/  outputs the following: 

You are using Chrome 100 on Windows 10


In a conclusion, the issue was successfully fixed.
