### ISSUE TITLE
Wrong autoload

### ISSUE THREAD

**Issue by lulco** [WhichBrowser/Parser-PHP#675]
```
"autoload": {
    "psr-4": {
        "WhichBrowser\\": [ "src/", "tests/src/" ]
    }
}
```

`tests/src/` is exluded via `.gitattributes`, so it doesn't appear in `vendor/whichbrowser/parser` directory after installation. It should be probably moved to `autoload-dev`

**Comment by NielsLeenheer** [comment]
Fixed in the latest release
