### ISSUE TITLE
macOS not detected

### ISSUE THREAD

**Issue by roelVerdonschot** [WhichBrowser/Parser-PHP#681]
I'm currently on Ventura 13.1 but this package shows macOS Catalina 10.15

**Comment by uuf6429** [comment]
That's a bit vague...maybe also provide the user agent string causing that?

**Comment by bago** [comment]
Read this: https://bugs.chromium.org/p/chromium/issues/detail?id=1175225

**Comment by NielsLeenheer** [comment]
Closing this, as it isn't a detection issue. It's a browser issue.
