### ISSUE TITLE
Unicode charcter \u 2002 included in detections

### ISSUE THREAD

**Issue by Taiwaninja** [WhichBrowser/Parser-PHP#96]
Hey

In quite a few detections we get a result of \u2002 inside the model instead of a space,
E.g. GALAXY Note 8 SC-01K instead of GALAXY Note 8 SC-01K.

Do note that this problem is sourced in data files and can be easily fixed with a find-replace

**Comment by Taiwaninja** [comment]
I would love to open a PR with a fix if I'll be granted push permissions

**Comment by rvalitov** [comment]
You don't need push permissions to contribute. You're PR is welcome!

**Comment by koconder** [comment]
I've added Pull Request #106 which fixes this issue

**Comment by koconder** [comment]
Added another PR in the JS Library for WhichBrowser patching the same issue there in the JS datafiles https://github.com/WhichBrowser/Parser-JavaScript/pull/29
