### ISSUE TITLE
Chrome 69 is already stable

### ISSUE THREAD

**Issue by StudioMaX** [WhichBrowser/Parser-PHP#99]
> Chrome Dev 69.0.3497.100 on Windows 10

for
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

Looks like `bin/update-chrome.php` wasn't executed or the new changes wasn't committed.

**Comment by NielsLeenheer** [comment]
Should be available as of 2.0.36
